---
title: "ggplot2"
author: "dkinkade"
date: "10/22/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# install and load tidyverse
#install.packages("tidyverse") # note on Windows use double quotes
library(tidyverse)

```

```{r}
#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")

```
```{r}
head(ca)
ggplot(data = ca) +
  geom_point(aes(x=year, y = visitors))


```
```{r}
head(ca)
ggplot(data = ca) +
  geom_point(aes(x=year, y = visitors, color = park_name))

```
```{r}
head(ca)
ggplot(data = ca) +
  # NOTE the below doesn't work b/c color was called OUTSIDE of easthetics"aes" and therefore R is looking for an object called "park_name"
  geom_point(aes(x=year, y = visitors), color = park_name)

```

```{r}
head(ca)
ggplot(data = ca) +
  geom_point(aes(x=year, y = visitors, color = park_name)) +
                 labs(x = "Year",
                      y = "Visitation",
                      title = "California National Park Visitors") +
  theme_bw() +
theme(legend.title = element_blank())


```
```{r}
head(se)
ggplot(data = se) +
  geom_point(aes(x=year, y = visitors, color = state)) +
  labs(x = "Year",
       y = "Visitors",
       title = "California SE Regional Park Visitors") +
  theme_classic() +
  #theme(legend.title.align = 0) +
  #theme(legend.title.align = 1) +
    theme(plot.title = element_text(hjust=0) +
theme(axis.text.x = element_text(angle = 45, size = 12))


```


